const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
const POST_ADDED_TO_LIST = 'POST_ADDED_TO_LIST';

export {
  FETCH_POSTS_REQUEST,
  FETCH_POSTS_SUCCESS,
  FETCH_POSTS_FAILURE,
  POST_ADDED_TO_LIST,
}